---
schema: v0.1

env_name: kunlun
resource_group_name: mykunlun
location: eastus

iaas: azure # this can be azure or some other platform

vm_groups:
  - name: jumpbox
    count: 1
    sku: Standard_B1s
    type: vm
    os_profile:
      admin_name: kunlun
      linux_configuration:
        ssh:
          public_keys:
            - "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAtk2lU6Q9YfjhY0kJFyVUbF+4j05VrOqMZbTHRyy6kZ9z4/daeuWFFlVV6MuzbcFmdd+4ZI9rFLWgew32ggHeMZvyOtukaC/bhSIXAapoP8+OzjgZq1uyQJmsA2r1BhD/fqAK5vQQpvGMDsrZ7ewoiTCnnL+TCVSIhRhX3T3oMo1p8jG7LwGJTRtYAHZED7KhME92ecrXGFM0ru5Q9vqFg7h3bz4SwnK6IcEy8+VBjrjOOlIof7wYSe2nUREkYra1PkVLmtbxVsWj6mzK9H9vfBSfTfa7FLETb1w6JRt+UW1wWwhGazHrkjodQzLRzNYKXSQ28k/1t4Yb5/GNvh7DFw== rsa-key-20160220"
    storage:
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS
        version: latest
      os_disk:
        managed_disk_type: Standard_LRS
        caching: ReadWrite
        create_option: FromImage
      data_disks:
        - managed_disk_type: Standard_LRS
          caching: ReadWrite
          create_option: Empty
          disk_size_gb: 100
        # - name_convension: uuid # this canbe uuid/group, if uuid, one uuid would be gnerated as name
    networks:
      - subnet_name: snet-1
        network_security_group_name: ssh_nsg
        public_ip: static

  - name: web-servers
    count: 1
    sku: Standard_B1s
    type: vmss # this can be vm or vmss
    os_profile:
      admin_name: kunlun
      linux_configuration:
        ssh:
          public_keys:
            - "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAtk2lU6Q9YfjhY0kJFyVUbF+4j05VrOqMZbTHRyy6kZ9z4/daeuWFFlVV6MuzbcFmdd+4ZI9rFLWgew32ggHeMZvyOtukaC/bhSIXAapoP8+OzjgZq1uyQJmsA2r1BhD/fqAK5vQQpvGMDsrZ7ewoiTCnnL+TCVSIhRhX3T3oMo1p8jG7LwGJTRtYAHZED7KhME92ecrXGFM0ru5Q9vqFg7h3bz4SwnK6IcEy8+VBjrjOOlIof7wYSe2nUREkYra1PkVLmtbxVsWj6mzK9H9vfBSfTfa7FLETb1w6JRt+UW1wWwhGazHrkjodQzLRzNYKXSQ28k/1t4Yb5/GNvh7DFw== rsa-key-20160220"
    storage:
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS
        version: latest
      os_disk:
        managed_disk_type: Standard_LRS
        caching: ReadWrite
        create_option: FromImage
      data_disks:
        - managed_disk_type: Standard_LRS
          caching: ReadWrite
          create_option: Empty
          disk_size_gb: 100
        # - name_convension: uuid # this canbe uuid/group, if uuid, one uuid would be gnerated as name
    networks:
      - subnet_name: snet-1
        load_balancer_name: load_balancer_1
        load_balancer_backend_address_pool_name: backend_address_pool_1
        network_security_group_name: webserver_nsg
    roles: # this is used to generate the deployment scripts
      - name: kunlun.php

vnets:
  - name: vnet-1
    subnets:
      - name: snet-1
        range: 10.0.0.0/24
        gateway: 10.0.0.1

load_balancers:
  - name: load_balancer_1
    sku: Standard
    backend_address_pools:
      - name: backend_address_pool_1
    health_probes:
      - name: http_probe
        protocol: Http # optional values: [Tcp, Http, Https]
        port: 80
        request_path: "/" # required if protocol is set to Http or Https. Otherwise, it is not allowed.
      - name: ssh_probe
        protocol: Tcp
        port: 22
    rules:
      - name: http_rule
        protocol: Tcp # optional values: [Tcp, Udp, All]
        frontend_port: 80
        backend_port: 80
        backend_address_pool_name: backend_address_pool_1
        health_probe_name: http_probe

network_security_groups:
  - name: webserver_nsg
    network_security_rules:
      - name: allow-http
        priority: 200
        direction: Inbound
        access: Allow
        protocol: Tcp
        source_port_range: "*"
        destination_port_range: 80
        source_address_prefix: "*"
        destination_address_prefix: "*"
  - name: ssh_nsg
    network_security_rules:
      - name: allow-ssh
        priority: 100
        direction: Inbound
        access: Allow
        protocol: Tcp
        source_port_range: "*"
        destination_port_range: 22
        source_address_prefix: "*"
        destination_address_prefix: "*"